gang/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.HomePageView.as_view(),name="home"),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('groups/',include('groups.urls',namespace="groups")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls',namespace="posts")),
    path('admin/', admin.site.urls),
]

groups/urls.py
from django.urls import path
from . import views


app_name = "groups"

urlpatterns = [
    path("",views.ListGroups.as_view(), name="all"),
    path("new/",views.CreateGroup.as_view(),name = "create"),
    path("post/in/<slug:slug>/",views.SingleGroup.as_view(),name="single"),
    path('join/<slug:slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify

User = get_user_model()

import misaka


# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=256,unique=True)
    description=  models.TextField(blank=True,null=True,)
    description_html = models.TextField(editable=False)
    creation_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def save(self, *args, **kwargs):
        self.description_html = misaka.html(self.description)
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    def __str__(self):
        return self.name
    
    class Meta: 
        ordering = ['creation_date']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name="memberships")
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="user_groups")

    def __str__(self):
        return self.user.name

    class Meta:
        unique_together = ['group','user']

groups/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin

from . import models


# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    model = models.Group
    fields = ['name','description']

class SingleGroup(generic.DetailView):
    model = models.Group

class ListGroups(generic.ListView):
    model = models.Group
    template_name = "groups/group_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(models.Group,slug=self.kwargs.get('slug'))
        try:
            models.GroupMember.objects.create(user=self.request.user,group = group)
        except :
            messages.warning(self.request,('warning already a member'))
        else:
            messages.success(self.request,"you are a new member")
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    def get(self, request, *args, **kwargs):
    
        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock pregroup %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <div class="h1">{{group.name}}</div>
    <div class="h2">members: {{group.members.count}}</div>

    <div class="content">
        {% if user in group.members.all%}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg">Leave</a>

        {%else%}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg">Join</a>
        {% endif %}
    </div>
{% endblock pregroup %}

{% block group_content %}

<div class="col-md-8">
    {% for post in group.posts.all %}
        {% include "posts/_post.html"%}
    {%endfor%}


</div>


{% endblock group_content %}

{% block postgroup %}


{% endblock postgroup %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}  
{% load bootstrap4 %}

{% block group_content %}
<h3>Create New group</h3>
<div class="container">
    <form action="{%url 'groups:create'%}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button name="" id="" class="btn btn-primary btn-fill btn-success" type="submit" value="create">Create Group</button>
    </form>
</div>
{% endblock group_content %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="content">
 {% if user.is_authenticated %}
    <a href="{%url 'posts:all'%}">@{{user.username}} </a>
 {% endif %}
 <h2> welcome to the groups page</h2>
</div>
{% if user.is_authenticated %}
<a href = "{% url 'groups:create'%}" class = "btn btn-md">Create new group</a>
{% endif %}


{% endblock pregroup %}

{% block group_content %}
<div class="content col-md-4">
    {% for group in object_list %}
    <a href="{% url 'groups:single' slug=group.slug %}">
        <h3 class = 'title'> {{group.name}}</h3>
        <div class="container-fluid">
            {{group.description_html|safe}}
        </div>
        <div class="container">
            {{group.posts.count|pluralize}}
        </div>
    </a>
    {% endfor %}
</div>

{% endblock group_content %}